title: FPGA/SoC/Verilog/HLS
description: FPGA, SoC, Verilog, and HLS labs
theme: just-the-docs

url: "https://wei-nextlab.github.io"
baseurl: "/ParallelProgrammingLabs"

aux_links:
  GitHub Repository: "https://github.com/wei-nextlab/ParallelProgrammingLabs"
